name : Dev-Cleanup

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  cleanup-images:
    runs-on: ubuntu-latest
    steps:
      - name: Prune
        uses: vlaurin/action-ghcr-prune@main
        with:
          token: ${{ secrets.GHCR_PAT }}
          organization: Haibread
          container: godisco
          dry-run: true # Dry-run first, then change to `false`
          older-than: 7 # days
          keep-last: 2
          untagged: true
          tag-regex: ^(dev-.*)
