name : Dev

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'
    - run: go version

    - name: Build
      run: go build -v ./...

    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Push to Github Packages
      uses: docker/build-push-action@v4
      with:
        tags: |
          ghcr.io/haibread/godisco:dev-latest
          ghcr.io/haibread/godisco:dev-${{ github.sha }}
        push: true
    
